package me.luisorlando.sounds;

public enum SoundType {
    BREAK_GLASS, BREAK_STONE, BREAK_WOOD, FLY_RED, FLY_WHITE, FLY_YELLOW, LOSE_BIRDS, WIN_BIRDS,
    OUCH_RED, OUCH_YELLOW, OUCH_WHITE, RESORTERA, START_LEVEL, BIRD_BREAK
}
